# Generated by Django 3.2.4 on 2021-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('cell_num', models.CharField(blank=True, default='', max_length=14)),
                ('phone_num', models.CharField(blank=True, default='', max_length=14, verbose_name='phone #')),
                ('usr_email', models.EmailField(default='', max_length=200, verbose_name='email address')),
                ('usr_addr1', models.CharField(max_length=50, verbose_name='address 1')),
                ('usr_addr2', models.CharField(blank=True, max_length=50)),
                ('usr_city', models.CharField(blank=True, default='', max_length=50)),
                ('usr_state', models.CharField(default='', max_length=50)),
                ('usr_zip', models.IntegerField(default='')),
                ('usr_country', models.CharField(default='', max_length=50)),
                ('urbanization', models.CharField(default='', max_length=50)),
                ('donation_amount', models.IntegerField(default='')),
            ],
        ),
    ]
