# Generated by Django 3.2.4 on 2021-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cell_num',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='donation',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='phone #'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='urbanization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_addr1',
            field=models.CharField(max_length=50, verbose_name='address 1'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_addr2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_email',
            field=models.EmailField(default='', max_length=200, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
