# Generated by Django 3.2.4 on 2021-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210626_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_opt',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='User', max_length=5, verbose_name='role'),
        ),
    ]
