# Generated by Django 3.2.4 on 2021-06-28 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_user_role_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
