# Generated by Django 3.2.4 on 2021-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donation_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(default='', max_length=255, verbose_name='type')),
                ('donation_amount', models.IntegerField(default='')),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_amount',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(default='', max_length=255, verbose_name='type'),
        ),
    ]
