# Generated by Django 3.2.4 on 2021-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20210628_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtype',
            name='donation_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
