# Generated by Django 3.2.4 on 2021-06-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_alter_donationtype_donation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
    ]
