# Generated by Django 3.2.4 on 2021-06-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='urbanization',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_zip',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
