# Generated by Django 3.2.4 on 2021-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_alter_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='usr_email',
            field=models.EmailField(default='', max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
