# Generated by Django 3.2.4 on 2021-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_auto_20210628_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[], default='', max_length=255, verbose_name='type'),
        ),
    ]
