# Generated by Django 3.2.4 on 2021-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_alter_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cell_num',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='cell #'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_country',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_state',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='usr_zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='zip'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_opt',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='User', max_length=5, verbose_name='role'),
        ),
    ]
