# Generated by Django 3.2.4 on 2021-06-29 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_auto_20210629_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(default='', max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
